theme = "xampa"
baseURL = "https://rj722.github.io/red/"
title = "Rahul Jha (~RJ722) Blog"
languageCode = "en-us"
pygmentsUseClasses = true
enableGitInfo = true

[params]
  author = "Rahul Jha"
  twitter = "antisemantic"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[permalinks]
    tags = "/blog/tags/:slug/"
