theme = "xampa"
baseURL = "https://rj722.github.io/xampa/"
languageCode = "en-us"
title = "Rahul Jha (~RJ722) Blog"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
