theme = "xampa"
baseURL = "https://staging.rj722.tk/"
languageCode = "en-us"
title = "Rahul Jha (~RJ722) Blog"

pygmentsUseClasses = true

enableGitInfo = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[permalinks]
    tags = "/blog/tags/:slug/"
